import faculty_member_ as p
import course_ as c

full_table = {1: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}},
              2: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}},
              3: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}},
              4: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}}}

slots = {1: "slot_1",
         2: "slot_2",
         3: "slot_3",
         4: "slot_4",
         5: "slot_5"}

days = {1: "sat",
        2: "sun",
        3: "mon",
        4: "tue",
        5: "wed",
        6: "thu"}

professors = []

assistants = []

courses = []


