import professor_ as p
import course_ as c
import level_ as l

full_table = {1: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
              "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}},
              2: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}},
              3: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}},
              4: {"sat": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "sun": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "mon": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "tue": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "wed": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None},
                  "thu": {"slot_1": None,
                          "slot_2": None,
                          "slot_3": None,
                          "slot_4": None,
                          "slot_5": None}}}

slots = {1: "slot_1",
         2: "slot_2",
         3: "slot_3",
         4: "slot_4",
         5: "slot_5"}

days = {1: "sat",
        2: "sun",
        3: "mon",
        4: "tue",
        5: "wed",
        6: "thu"}

professors = [p.faculty_member("1", "Ahmed Mohamed", "101", "301", "305"),
              p.faculty_member("2", "Hassan Ali", "102", "302", "301"),
              p.faculty_member("3", "Mohamed Ibrahim", "103", "303", "301"),
              p.faculty_member("4", "Omar Samir", "104", "304", "301"),
              p.faculty_member("5", "Khaled Ahmed", "105", "305", "301"),
              p.faculty_member("6", "Amr Hossam", "106", "306", "301"),
              p.faculty_member("7", "Ali Mahmoud", "201", "401", "301"),
              p.faculty_member("8", "Tarek Hassan", "202", "402", "301"),
              p.faculty_member("9", "Mahmoud Sami", "203", "403", "301"),
              p.faculty_member("10", "Youssef Ahmed", "204", "404", "301"),
              p.faculty_member("11", "Karim Mohamed", "205", "405", "301"),
              p.faculty_member("12", "Mamdouh Adel", "206", "406", "301")]

assistants = [p.faculty_member("13", "Ahmad Salah", "101", "301", "301"),
              p.faculty_member("14", "Adham Mostafa", "102", "302", "301"),
              p.faculty_member("15", "Hisham Amr", "103", "303", "301"),
              p.faculty_member("16", "Wael Mahmoud", "104", "304", "301"),
              p.faculty_member("17", "Mazen Samy", "105", "305", "301"),
              p.faculty_member("18", "Hamza Sherif", "106", "306", "301"),
              p.faculty_member("19", "Mohsen Ali", "201", "401", "301"),
              p.faculty_member("20", "Sherif Ezzat", "202", "402", "301"),
              p.faculty_member("21", "Nabil Tawfiq", "203", "403", "301"),
              p.faculty_member("22", "Tamer Adel", "204", "404", "301"),
              p.faculty_member("23", "Hany Youssef", "205", "405", "301"),
              p.faculty_member("24", "Ali Madkour", "206", "406", "301")]

courses = [c.Course("101", "Introduction to Programming", 2, 2, 1),
           c.Course("102", "Data Structures and Algorithms", 2, 2, 1),
           c.Course("103", "Database Management Systems", 2, 2, 1),
           c.Course("104", "Computer Networks", 2, 2, 1),
           c.Course("105", "Operating Systems", 2, 2, 1),
           c.Course("106", "Software Engineering", 2, 2, 1),
           c.Course("201", "Cybersecurity Basics", 2, 2, 1),
           c.Course("202", "Web Development Fundamentals", 2, 2, 1),
           c.Course("203", "Artificial Intelligence Concepts", 2, 2, 1),
           c.Course("204", "Machine Learning Applications", 2, 2, 1),
           c.Course("205", "Data Science Essentials", 2, 2, 1),
           c.Course("206", "Network Security Protocols", 2, 2, 1),
           c.Course("301", "Introduction to Cryptography", 2, 2, 1),
           c.Course("302", "Web Development Advanced", 2, 2, 1),
           c.Course("303", "Advanced AI Concepts", 2, 2, 1),
           c.Course("304", "Advanced Machine Learning", 2, 2, 1),
           c.Course("305", "Advanced Data Science", 2, 2, 1),
           c.Course("306", "Advanced Network Security", 2, 2, 1),
           c.Course("401", "Advanced Cryptography", 2, 2, 1),
           c.Course("402", "Cloud Computing", 2, 2, 1),
           c.Course("403", "Computer Vision", 2, 2, 1),
           c.Course("404", "Advanced Robotics", 2, 2, 1),
           c.Course("405", "Natural Language Processing", 2, 2, 1),
           c.Course("406", "Cyber-Physical Systems", 2, 2, 1)]

# levels = [l.Level("1", 2),
#           l.level("2", 2),
#           l.level("3", 2),
#           l.level("4", 2)]
